import type {
  EventType,
  NotificationSettings,
  Pet,
  PetEvent,
  PetGender,
  PetType,
  User,
} from './types';

export const mockUser: User = {
  id: 1,
  firstName: 'Алексей',
  lastName: 'Петров',
  login: 'alex_petrov',
  email: 'alex@example.com',
  telegramUsername: '@alex_petrov',
  telegramConnected: false,
  avatarUrl: 'https://i.pravatar.cc/150?img=12',
  notifications: {
    vetVisit: true,
    vaccination: true,
    medication: false,
    grooming: true,
    event: false,
    channels: {
      email: true,
      telegram: false,
    },
  },
};

export const petTypeIcon: Record<PetType, string> = {
  cat: '🐱',
  dog: '🐶',
  bird: '🐦',
  rabbit: '🐰',
  other: '🐾',
};

export const notificationLabels: {
  key: keyof Omit<NotificationSettings, 'channels'>;
  label: string;
  icon: string;
}[] = [
  { key: 'vetVisit', label: 'Приём ветеринара', icon: '🏥' },
  { key: 'vaccination', label: 'Прививки', icon: '💉' },
  { key: 'medication', label: 'Приём лекарств', icon: '💊' },
  { key: 'grooming', label: 'Груминг', icon: '✂️' },
  { key: 'event', label: 'Прочие события', icon: '📅' },
];

export const mockPets: Pet[] = [
  {
    id: 1,
    name: 'Барсик',
    type: 'cat',
    breed: 'Британская короткошёрстная',
    gender: 'male',
    avatarUrl: 'https://placecats.com/60/60',
    birthDate: '2021-03-15',
    color: 'Серый табби',
    chipNumber: '',
    weight: 5.1,
    weightHistory: [
      { date: '2024-09', value: 4.6 },
      { date: '2024-12', value: 4.9 },
      { date: '2025-03', value: 5.0 },
      { date: '2025-05', value: 5.1 },
    ],
    notes: 'Аллергия на курицу. Предпочитает влажный корм.',
  },
  {
    id: 2,
    name: 'Рыжик',
    type: 'cat',
    breed: 'Мейн-кун',
    gender: 'male',
    avatarUrl: 'https://placecats.com/61/61',
    birthDate: '2020-07-22',
    color: 'Рыжий',
    chipNumber: '',
    weight: 7.3,
    weightHistory: [
      { date: '2024-09', value: 6.8 },
      { date: '2024-12', value: 7.0 },
      { date: '2025-03', value: 7.2 },
      { date: '2025-05', value: 7.3 },
    ],
    notes: '',
  },
  {
    id: 3,
    name: 'Бобик',
    type: 'dog',
    breed: 'Лабрадор',
    gender: 'male',
    avatarUrl: 'https://placedog.net/60/60',
    birthDate: '2019-11-01',
    color: 'Чёрный',
    chipNumber: '643094100000001',
    weight: 28.5,
    weightHistory: [
      { date: '2024-09', value: 27.0 },
      { date: '2024-12', value: 27.8 },
      { date: '2025-03', value: 28.2 },
      { date: '2025-05', value: 28.5 },
    ],
    notes: 'Дисплазия тазобедренного сустава. Ограничить прыжки.',
  },
  {
    id: 4,
    name: 'Луна',
    type: 'cat',
    breed: 'Шотландская вислоухая',
    gender: 'female',
    avatarUrl: 'https://placecats.com/62/62',
    birthDate: '2022-05-10',
    color: 'Белая',
    chipNumber: '643094100000002',
    weight: 3.8,
    weightHistory: [
      { date: '2024-09', value: 3.5 },
      { date: '2024-12', value: 3.6 },
      { date: '2025-03', value: 3.7 },
      { date: '2025-05', value: 3.8 },
    ],
    notes: 'Стерилизована. Склонна к мочекаменной болезни, специальный корм.',
  },
  {
    id: 5,
    name: 'Белка',
    type: 'dog',
    breed: 'Золотистый ретривер',
    gender: 'female',
    avatarUrl: 'https://placedog.net/61/61',
    birthDate: '2023-02-14',
    color: 'Золотистый',
    chipNumber: '',
    weight: 22.0,
    weightHistory: [
      { date: '2024-09', value: 18.5 },
      { date: '2024-12', value: 20.0 },
      { date: '2025-03', value: 21.2 },
      { date: '2025-05', value: 22.0 },
    ],
    notes: 'Молодая, активная. Курс дрессировки пройден.',
  },
  {
    id: 6,
    name: 'Кеша',
    type: 'bird',
    breed: 'Волнистый попугай',
    gender: 'male',
    avatarUrl: 'https://placedog.net/60/60',
    birthDate: '2023-08-01',
    color: 'Зелёный с жёлтым',
    chipNumber: '',
    weight: 0.04,
    weightHistory: [
      { date: '2024-09', value: 0.038 },
      { date: '2025-01', value: 0.039 },
      { date: '2025-05', value: 0.04 },
    ],
    notes: 'Умеет говорить ~15 слов. Боится пылесоса.',
  },
];
export const mockPet = mockPets[0];

export const petTypeLabels: Record<PetType, string> = {
  cat: '🐱 Кошка',
  dog: '🐶 Собака',
  bird: '🐦 Птица',
  rabbit: '🐰 Кролик',
  other: '🐾 Другое',
};

export const genderLabels: Record<PetGender, string> = {
  male: 'Мальчик',
  female: 'Девочка',
};

export const mockEvents: PetEvent[] = [
  // --- Барсик (cat, id:1) ---
  {
    id: 1,
    petId: 1,
    petName: 'Барсик',
    type: 'vet',
    status: 'done',
    date: '2025-01-15',
    cost: 2200,
    notes: 'Плановый осмотр. Небольшой зубной камень.',
    photos: [{ id: 1, url: 'https://placecats.com/80/80' }],
    clinic: 'ВетКлиника Плюс',
    doctor: 'Иванова А.В.',
    diagnosis: 'Зубной камень 1 ст.',
    nextVisitDate: '2025-05-20',
  },
  {
    id: 2,
    petId: 1,
    petName: 'Барсик',
    type: 'vaccination',
    status: 'done',
    date: '2025-02-10',
    cost: 1800,
    notes: '',
    photos: [],
    vaccineName: 'Мультифел-4',
    nextDate: '2026-02-10',
  },
  {
    id: 3,
    petId: 1,
    petName: 'Барсик',
    type: 'medication',
    status: 'done',
    date: '2025-03-01',
    cost: 450,
    notes: 'Профилактика. Курс 1 таблетка.',
    photos: [],
    medicationName: 'Мильбемакс',
    quantity: 2,
    remaining: 0,
    periodDays: 90,
  },
  {
    id: 4,
    petId: 1,
    petName: 'Барсик',
    type: 'vet',
    status: 'done',
    date: '2025-05-20',
    cost: 2500,
    notes: 'Плановый осмотр. Всё в норме.',
    photos: [
      { id: 2, url: 'https://placecats.com/81/81' },
      { id: 3, url: 'https://placecats.com/82/82' },
    ],
    clinic: 'ВетКлиника Плюс',
    doctor: 'Иванова А.В.',
    diagnosis: 'Здоров',
    nextVisitDate: '2025-11-20',
  },
  {
    id: 5,
    petId: 1,
    petName: 'Барсик',
    type: 'medication',
    status: 'planned',
    date: '2025-06-10',
    cost: 450,
    notes: 'Курс 10 дней',
    photos: [],
    medicationName: 'Мильбемакс',
    quantity: 2,
    remaining: 1,
    periodDays: 90,
  },
  {
    id: 6,
    petId: 1,
    petName: 'Барсик',
    type: 'purchase',
    status: 'done',
    date: '2025-04-05',
    cost: 1200,
    notes: 'Месячный запас',
    photos: [],
    category: 'food',
    itemName: 'Royal Canin Sensitivity',
  },

  // --- Рыжик (cat, id:2) ---
  {
    id: 7,
    petId: 2,
    petName: 'Рыжик',
    type: 'vet',
    status: 'done',
    date: '2025-02-20',
    cost: 3100,
    notes: 'Жалобы на вялость. Анализы в норме.',
    photos: [],
    clinic: 'ЗооВет Центр',
    doctor: 'Смирнов П.Д.',
    diagnosis: 'Здоров',
    nextVisitDate: '2025-08-20',
  },
  {
    id: 8,
    petId: 2,
    petName: 'Рыжик',
    type: 'vaccination',
    status: 'done',
    date: '2025-03-15',
    cost: 1800,
    notes: '',
    photos: [],
    vaccineName: 'Мультифел-4',
    nextDate: '2026-03-15',
  },
  {
    id: 9,
    petId: 2,
    petName: 'Рыжик',
    type: 'grooming',
    status: 'done',
    date: '2025-04-10',
    cost: 2500,
    notes: 'Стрижка + купание',
    photos: [{ id: 4, url: 'https://placecats.com/83/83' }],
    salon: 'ГрумингСтудия Пушок',
  },
  {
    id: 10,
    petId: 2,
    petName: 'Рыжик',
    type: 'medication',
    status: 'planned',
    date: '2025-06-15',
    cost: 450,
    notes: '',
    photos: [],
    medicationName: 'Мильбемакс',
    quantity: 2,
    remaining: 2,
    periodDays: 90,
  },
  {
    id: 11,
    petId: 2,
    petName: 'Рыжик',
    type: 'purchase',
    status: 'done',
    date: '2025-05-01',
    cost: 3400,
    notes: '',
    photos: [],
    category: 'food',
    itemName: 'Royal Canin Maine Coon',
  },

  // --- Бобик (dog, id:3) ---
  {
    id: 12,
    petId: 3,
    petName: 'Бобик',
    type: 'vet',
    status: 'done',
    date: '2025-01-20',
    cost: 4500,
    notes: 'Осмотр суставов. Назначен хондропротектор.',
    photos: [],
    clinic: 'ВетКлиника Плюс',
    doctor: 'Козлова М.С.',
    diagnosis: 'Дисплазия ТБС 2 ст.',
    nextVisitDate: '2025-07-20',
  },
  {
    id: 13,
    petId: 3,
    petName: 'Бобик',
    type: 'medication',
    status: 'done',
    date: '2025-02-01',
    cost: 2800,
    notes: 'Курс 30 дней',
    photos: [],
    medicationName: 'Артрогликан',
    quantity: 30,
    remaining: 0,
    periodDays: 180,
  },
  {
    id: 14,
    petId: 3,
    petName: 'Бобик',
    type: 'vaccination',
    status: 'done',
    date: '2025-03-05',
    cost: 2100,
    notes: '',
    photos: [],
    vaccineName: 'Nobivac DHPPi + Rabies',
    nextDate: '2026-03-05',
  },
  {
    id: 15,
    petId: 3,
    petName: 'Бобик',
    type: 'purchase',
    status: 'done',
    date: '2025-04-15',
    cost: 5200,
    notes: '2 мешка по 12 кг',
    photos: [],
    category: 'food',
    itemName: 'Royal Canin Labrador Adult',
  },
  {
    id: 16,
    petId: 3,
    petName: 'Бобик',
    type: 'vet',
    status: 'planned',
    date: '2025-06-20',
    cost: 4500,
    notes: 'Контрольный осмотр суставов',
    photos: [],
    clinic: 'ВетКлиника Плюс',
    doctor: 'Козлова М.С.',
    diagnosis: '',
    nextVisitDate: undefined,
  },

  // --- Луна (cat, id:4) ---
  {
    id: 17,
    petId: 4,
    petName: 'Луна',
    type: 'vet',
    status: 'done',
    date: '2025-02-05',
    cost: 1900,
    notes: 'Профилактический осмотр после стерилизации.',
    photos: [],
    clinic: 'ЗооВет Центр',
    doctor: 'Смирнов П.Д.',
    diagnosis: 'Здорова',
    nextVisitDate: '2025-08-05',
  },
  {
    id: 18,
    petId: 4,
    petName: 'Луна',
    type: 'vaccination',
    status: 'done',
    date: '2025-03-20',
    cost: 1800,
    notes: '',
    photos: [],
    vaccineName: 'Мультифел-4',
    nextDate: '2026-03-20',
  },
  {
    id: 19,
    petId: 4,
    petName: 'Луна',
    type: 'purchase',
    status: 'done',
    date: '2025-04-20',
    cost: 1600,
    notes: 'Диетический корм при МКБ',
    photos: [],
    category: 'food',
    itemName: "Hill's Prescription Diet c/d",
  },
  {
    id: 20,
    petId: 4,
    petName: 'Луна',
    type: 'grooming',
    status: 'planned',
    date: '2025-06-25',
    cost: 1200,
    notes: 'Стрижка когтей + чистка ушей',
    photos: [],
    salon: 'ГрумингСтудия Пушок',
  },

  // --- Белка (dog, id:5) ---
  {
    id: 21,
    petId: 5,
    petName: 'Белка',
    type: 'vet',
    status: 'done',
    date: '2025-01-10',
    cost: 2800,
    notes: 'Первичный осмотр щенка.',
    photos: [{ id: 5, url: 'https://placedog.net/80/80' }],
    clinic: 'ДогТор',
    doctor: 'Петрова Е.А.',
    diagnosis: 'Здорова',
    nextVisitDate: '2025-07-10',
  },
  {
    id: 22,
    petId: 5,
    petName: 'Белка',
    type: 'vaccination',
    status: 'done',
    date: '2025-02-15',
    cost: 2100,
    notes: '',
    photos: [],
    vaccineName: 'Nobivac DHPPi',
    nextDate: '2026-02-15',
  },
  {
    id: 23,
    petId: 5,
    petName: 'Белка',
    type: 'grooming',
    status: 'done',
    date: '2025-03-25',
    cost: 3200,
    notes: 'Купание, сушка, расчёс',
    photos: [],
    salon: 'ГрумингСтудия Пушок',
  },
  {
    id: 24,
    petId: 5,
    petName: 'Белка',
    type: 'purchase',
    status: 'done',
    date: '2025-05-10',
    cost: 890,
    notes: '',
    photos: [],
    category: 'toy',
    itemName: 'Канатная игрушка-тягалка',
  },
  {
    id: 25,
    petId: 5,
    petName: 'Белка',
    type: 'medication',
    status: 'planned',
    date: '2025-06-05',
    cost: 620,
    notes: '',
    photos: [],
    medicationName: 'Дронтал Плюс',
    quantity: 2,
    remaining: 2,
    periodDays: 90,
  },

  // --- Кеша (bird, id:6) ---
  {
    id: 26,
    petId: 6,
    petName: 'Кеша',
    type: 'vet',
    status: 'done',
    date: '2025-01-25',
    cost: 1400,
    notes: 'Осмотр оперения. Дефицит витамина D.',
    photos: [],
    clinic: 'Экзотик Вет',
    doctor: 'Орлов В.Н.',
    diagnosis: 'Гиповитаминоз D',
    nextVisitDate: '2025-07-25',
  },
  {
    id: 27,
    petId: 6,
    petName: 'Кеша',
    type: 'medication',
    status: 'done',
    date: '2025-02-01',
    cost: 380,
    notes: 'Добавлять в воду 2 капли в день, 30 дней',
    photos: [],
    medicationName: 'Витамин D3 (птицы)',
    quantity: 1,
    remaining: 0,
    periodDays: 365,
  },
  {
    id: 28,
    petId: 6,
    petName: 'Кеша',
    type: 'purchase',
    status: 'done',
    date: '2025-03-10',
    cost: 650,
    notes: '',
    photos: [],
    category: 'accessory',
    itemName: 'Минеральный камень + жердочки',
  },
  {
    id: 29,
    petId: 6,
    petName: 'Кеша',
    type: 'note',
    status: 'done',
    date: '2025-04-18',
    notes: 'Впервые сказал "Кеша хороший". Записал на видео.',
    photos: [],
  },
  {
    id: 30,
    petId: 6,
    petName: 'Кеша',
    type: 'vet',
    status: 'planned',
    date: '2025-07-25',
    cost: 1400,
    notes: 'Контрольный осмотр оперения',
    photos: [],
    clinic: 'Экзотик Вет',
    doctor: 'Орлов В.Н.',
    diagnosis: '',
    nextVisitDate: undefined,
  },
];

export const typeConfig: Record<EventType, { label: string; icon: string; color: string }> = {
  vet: { label: 'Приём ветеринара', icon: '🏥', color: 'danger' },
  vaccination: { label: 'Прививка', icon: '💉', color: 'primary' },
  medication: { label: 'Лекарство', icon: '💊', color: 'warning' },
  grooming: { label: 'Груминг', icon: '✂️', color: 'info' },
  purchase: { label: 'Покупка', icon: '🛍️', color: 'success' },
  note: { label: 'Заметка', icon: '📝', color: 'secondary' },
};

export const purchaseCategoryLabels: Record<string, string> = {
  food: 'Корм',
  toy: 'Игрушка',
  accessory: 'Аксессуар',
  other: 'Прочее',
};

export const eventTypeConfig: Record<EventType, { icon: string; color: string }> = {
  vet: { icon: '🏥', color: 'danger' },
  vaccination: { icon: '💉', color: 'primary' },
  medication: { icon: '💊', color: 'warning' },
  grooming: { icon: '✂️', color: 'info' },
  purchase: { icon: '🛍️', color: 'success' },
  note: { icon: '📝', color: 'secondary' },
};
